"""Opening the dashboard without a terminal.

`optscan serve` is the right command and the wrong front door. It needs a shell, the
right working directory, and the venv interpreter rather than the system one, and it
leaves a console window that has to stay open. None of that is hard, and all of it is
enough friction to stop somebody glancing at the board.

So this generates two things: a `.cmd` that knows all of the above, and a Desktop
shortcut pointing at it.

## Why a .cmd and not pythonw

`pythonw.exe` would start the server with no console at all, which looks the most like
an app and is the worst of the options: there would be no way to stop it except Task
Manager. The launcher runs in a console window that is started minimized, so it sits in
the taskbar, and closing it stops the server. That window *is* the app, which is a
model somebody can reason about without being told.

## Why the launcher is generated rather than committed

It bakes in the configured host and port. Config is the single source for those
everywhere else, and a checked in script with 8000 hardcoded would quietly disagree
with `OPTSCAN_API_PORT` the day somebody changed it.

## Why it checks health before starting anything

Double clicking twice should open a second browser tab, not a second server fighting
for the port. The launcher asks `/api/health` first and, if something already answers,
does nothing but open the browser.
"""

from __future__ import annotations

import socket
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from optscan.config import REPO_ROOT, Settings
from optscan.logging import get_logger

log = get_logger("optscan.jobs.launcher")

SHORTCUT_NAME = "optscan dashboard.lnk"
LAUNCHER_NAME = "optscan-dashboard.cmd"
ICON_NAME = "optscan.ico"

#: How long the launcher waits for the server to answer before giving up on opening a
#: browser. Generous: the first start imports pandas and pyarrow, which is not fast.
STARTUP_TIMEOUT_SECONDS = 60


@dataclass(frozen=True, slots=True)
class ShortcutResult:
    ok: bool
    message: str
    launcher: Path | None = None
    shortcut: Path | None = None


def scripts_dir() -> Path:
    return REPO_ROOT / "scripts"


def launcher_path() -> Path:
    return scripts_dir() / LAUNCHER_NAME


def icon_path() -> Path:
    return scripts_dir() / ICON_NAME


def browse_host(settings: Settings) -> str:
    """The host a browser should be pointed at.

    `0.0.0.0` is a valid thing to bind and not a valid thing to visit, so it becomes
    loopback here rather than producing a shortcut that opens a page that cannot load.
    """
    return "127.0.0.1" if settings.api_host in ("0.0.0.0", "::", "") else settings.api_host


def dashboard_url(settings: Settings) -> str:
    return f"http://{browse_host(settings)}:{settings.api_port}"


def desktop_dir() -> Path:
    """The real Desktop, which is often not `%USERPROFILE%\\Desktop`.

    OneDrive's folder redirection moves it, and on this machine it is redirected. Asking
    Windows for the known folder is the only way to be right: writing a shortcut to the
    unredirected path succeeds, and puts it somewhere the user never looks.
    """
    if sys.platform != "win32":
        return Path.home() / "Desktop"
    completed = subprocess.run(
        [
            "powershell",
            "-NoProfile",
            "-NonInteractive",
            "-Command",
            "[Environment]::GetFolderPath('Desktop')",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    resolved = completed.stdout.strip()
    return Path(resolved) if resolved else Path.home() / "Desktop"


def launcher_script(settings: Settings) -> str:
    """The batch file the shortcut runs.

    Written as one string rather than assembled, because a batch file is read by whoever
    has to debug it at some point and the order of the lines is the explanation.
    """
    url = dashboard_url(settings)
    python = REPO_ROOT / "venv" / "Scripts" / "python.exe"
    attempts = STARTUP_TIMEOUT_SECONDS * 2  # the waiter polls twice a second

    probe = (
        f"try {{ Invoke-WebRequest {url}/api/health -UseBasicParsing "
        f"-TimeoutSec 2 | Out-Null; exit 0 }} catch {{ exit 1 }}"
    )
    waiter = (
        f"for ($i=0; $i -lt {attempts}; $i++) {{ try {{ "
        f"Invoke-WebRequest {url}/api/health -UseBasicParsing -TimeoutSec 2 | Out-Null; "
        f"Start-Process '{url}'; break }} catch {{ Start-Sleep -Milliseconds 500 }} }}"
    )

    return f"""@echo off
title optscan dashboard - close this window to stop it
cd /d "%~dp0.."

rem Generated by `optscan shortcut`. Regenerate it rather than editing it: the host
rem and port are baked in from config and will drift if they are changed by hand.

rem Already serving? Then this is a second double click. Open a tab, change nothing.
powershell -NoProfile -NonInteractive -Command "{probe}"
if not errorlevel 1 (
  start "" "{url}"
  exit /b 0
)

rem Open the browser as soon as the server answers, then hand this window to uvicorn.
rem The wait matters: the first import of pandas and pyarrow takes seconds, and a
rem browser opened before then lands on a connection error and has to be reloaded.
start /b "" powershell -NoProfile -NonInteractive -Command "{waiter}"

echo Starting the optscan dashboard at {url}
echo A browser will open when it is ready. Closing this window stops the server.
echo.
"{python}" -m optscan serve
"""


def write_launcher(settings: Settings) -> Path:
    path = launcher_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(launcher_script(settings), encoding="utf-8")
    return path


def shortcut_script(target: Path, shortcut: Path, icon: Path) -> str:
    """PowerShell that creates the .lnk.

    WindowStyle 7 is minimized. The console still exists and is still closable, it just
    does not take the screen when the real destination is the browser.
    """
    return (
        "$shell = New-Object -ComObject WScript.Shell; "
        f"$link = $shell.CreateShortcut('{shortcut}'); "
        f"$link.TargetPath = '{target}'; "
        f"$link.WorkingDirectory = '{target.parent}'; "
        f"$link.IconLocation = '{icon}'; "
        "$link.WindowStyle = 7; "
        "$link.Description = 'Options selling scanner dashboard'; "
        "$link.Save()"
    )


def install_shortcut(settings: Settings) -> ShortcutResult:
    """Write the launcher and put a shortcut to it on the Desktop."""
    if sys.platform != "win32":
        return ShortcutResult(
            ok=False,
            message=f"Desktop shortcuts are Windows only, this is {sys.platform}.",
        )

    launcher = write_launcher(settings)
    icon = icon_path()
    if not icon.exists():
        write_icon(icon)

    shortcut = desktop_dir() / SHORTCUT_NAME
    if not shortcut.parent.exists():
        return ShortcutResult(
            ok=False,
            message=f"No Desktop directory at {shortcut.parent}.",
            launcher=launcher,
        )

    completed = subprocess.run(
        [
            "powershell",
            "-NoProfile",
            "-NonInteractive",
            "-Command",
            shortcut_script(launcher, shortcut, icon),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        message = (completed.stderr or completed.stdout).strip()
        log.error("failed to create the shortcut", error=message)
        return ShortcutResult(ok=False, message=f"Could not create the shortcut: {message}")

    log.info("installed desktop shortcut", shortcut=str(shortcut), launcher=str(launcher))
    return ShortcutResult(
        ok=True,
        message=f'Double click "{shortcut.stem}" on your Desktop.',
        launcher=launcher,
        shortcut=shortcut,
    )


def remove_shortcut() -> ShortcutResult:
    """Take the shortcut off the Desktop. Leaves the launcher, which is harmless."""
    shortcut = desktop_dir() / SHORTCUT_NAME
    if not shortcut.exists():
        return ShortcutResult(ok=True, message=f"Nothing to remove at {shortcut}.")
    shortcut.unlink()
    return ShortcutResult(ok=True, message=f"Removed {shortcut}.", shortcut=shortcut)


# --- The icon -----------------------------------------------------------------------
#
# Written by hand rather than with Pillow, which is not a dependency and is not worth
# becoming one for 48 squares of colour. An .ico is a small header plus, here, a bottom
# up BGRA bitmap, which is little enough format to be worth not taking a library for.

SIZE = 32
BACKGROUND = (0x0E, 0x11, 0x16)  # --bg from the dashboard stylesheet
BARS = (
    # (x, width, top, colour) in icon pixels, drawn from the palette the UI already uses
    (6, 5, 20, (0x5D, 0x68, 0x75)),  # --dim
    (13, 5, 14, (0x4C, 0x9B, 0xE8)),  # --accent
    (20, 5, 7, (0x46, 0xB1, 0x7B)),  # --good
)


def _pixels() -> list[list[tuple[int, int, int]]]:
    grid = [[BACKGROUND for _ in range(SIZE)] for _ in range(SIZE)]
    for x0, width, top, colour in BARS:
        for x in range(x0, x0 + width):
            for y in range(top, SIZE - 5):
                grid[y][x] = colour
    # A baseline, so the bars read as a chart rather than as three rectangles.
    for x in range(4, SIZE - 4):
        grid[SIZE - 5][x] = (0x26, 0x2E, 0x39)  # --line
    return grid


def icon_bytes() -> bytes:
    """A single 32x32 32bpp icon, as .ico bytes."""
    grid = _pixels()

    # BITMAPINFOHEADER: height is doubled because an icon carries colour plus a mask.
    header = b"".join(
        (
            (40).to_bytes(4, "little"),
            SIZE.to_bytes(4, "little"),
            (SIZE * 2).to_bytes(4, "little"),
            (1).to_bytes(2, "little"),
            (32).to_bytes(2, "little"),
            (0).to_bytes(4, "little"),
            (SIZE * SIZE * 4).to_bytes(4, "little"),
            *((0).to_bytes(4, "little") for _ in range(4)),
        )
    )

    # BGRA, bottom row first.
    body = bytearray()
    for y in reversed(range(SIZE)):
        for x in range(SIZE):
            red, green, blue = grid[y][x]
            body += bytes((blue, green, red, 0xFF))

    # The AND mask is unused at 32bpp but the format still wants the rows.
    mask = bytes(SIZE // 8 * SIZE)
    image = header + bytes(body) + mask

    directory = b"".join(
        (
            SIZE.to_bytes(1, "little"),
            SIZE.to_bytes(1, "little"),
            (0).to_bytes(1, "little"),
            (0).to_bytes(1, "little"),
            (1).to_bytes(2, "little"),
            (32).to_bytes(2, "little"),
            len(image).to_bytes(4, "little"),
            (22).to_bytes(4, "little"),
        )
    )
    return b"\x00\x00\x01\x00\x01\x00" + directory + image


def write_icon(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(icon_bytes())
    return path


#: The address that means "listen on every interface". Binding here is what makes the
#: dashboard reachable from a phone, and it is opt in for a reason: this app has no
#: authentication of any kind, so anyone on the same network can read the positions,
#: the journal and the imported broker P/L by typing an address.
ALL_INTERFACES = "0.0.0.0"


def lan_address() -> str | None:
    """This machine's address on the local network, or None if it cannot be found.

    Opens a UDP socket toward a public address and reads back which local interface
    the routing table chose. **Nothing is sent.** A UDP connect is purely a local
    operation that fixes the socket's peer, which is what makes this work with no
    network traffic and no dependency on the host being reachable.

    Preferred over `gethostbyname(gethostname())`, which on Windows routinely returns
    127.0.0.1 or the address of a virtual adapter that a phone cannot reach.
    """
    probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        probe.connect(("8.8.8.8", 80))
        address = probe.getsockname()[0]
    except OSError:
        return None
    finally:
        probe.close()
    return address if address and not address.startswith("127.") else None


def firewall_command(port: int) -> str:
    """The PowerShell that opens the port to the local network.

    Returned as text rather than run. Changing the firewall is a system security
    setting and needs an elevated prompt, so it belongs to the person at the keyboard.

    Scoped to `Private` profile and the local subnet: a rule that opened the port on a
    public profile would follow the laptop onto café wifi, which is a different and
    much worse exposure than a home network.
    """
    return (
        f"New-NetFirewallRule -DisplayName 'optscan dashboard' -Direction Inbound "
        f"-LocalPort {port} -Protocol TCP -Action Allow -Profile Private "
        f"-RemoteAddress LocalSubnet"
    )


def port_is_taken(port: int, host: str = "127.0.0.1", timeout: float = 0.35) -> bool:
    """Whether something already answers on this port.

    Checked against loopback specifically, and that is the whole point rather than an
    implementation detail. Binding `0.0.0.0` **succeeds** on Windows while another
    process holds `127.0.0.1` on the same port: they are different addresses, so there
    is no conflict to report and uvicorn starts cleanly.

    What happens next is the trap. Windows routes a request to the most specific
    binding, so `localhost` reaches the *older* process and the LAN address reaches the
    new one. The two then serve different code from the same port, and the symptom is a
    dashboard whose new endpoints return the SPA's HTML while `/api/health` works fine,
    which reads exactly like a routing bug in the app.

    Measured 2026-09-08: a server started at 16:13 held 127.0.0.1:8000 while a new one
    started at 21:50 held 0.0.0.0:8000. `/api/home` returned HTML on localhost and JSON
    on the LAN address, from the same URL path, at the same moment.
    """
    probe = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    probe.settimeout(timeout)
    try:
        return probe.connect_ex((host, port)) == 0
    except OSError:
        return False
    finally:
        probe.close()


def stale_server_warning(port: int) -> str:
    """What to print when the port is already answering. Advice, not an error.

    Not fatal: serving two ports deliberately is legitimate, and refusing to start
    would be worse than a sentence. But it is loud, because the failure it prevents
    costs half an hour and looks like a bug in the code rather than in the machine.
    """
    return (
        f"Something is already listening on port {port}.\n"
        f"  Binding every interface still succeeds, but localhost:{port} will reach "
        "the OTHER process\n"
        "  and only the network address will reach this one. If the dashboard looks "
        "out of date,\n"
        "  or new endpoints return HTML instead of JSON, that is why.\n"
        "  Find it with:  Get-NetTCPConnection -LocalPort "
        f"{port} -State Listen | Select-Object LocalAddress, OwningProcess"
    )
